openapi: 3.1.0
info:
  version: 1.0.0
  title: Docuementacion API BDV
tags:
servers:
  - url: 'https://{tenant}/api/v1'
    variables:
      tenant:
        default: www
        description: Your tenant id
  - url: 'https://example.com/api/v1'
paths:
  /HABA:  
    $ref: paths/accountingtermfinan/HABA.yaml  
  /HABB:  
    $ref: paths/accountingtermfinan/HABB.yaml  
  /B480:  
    $ref: paths/accountinquiry/B480.yaml  
  /B41A:  
    $ref: paths/accountinquiry/B41A.yaml  
  /BKXB:  
    $ref: paths/accountinquiry/BKXB.yaml  
  /WP46:  
    $ref: paths/activitycategoryspecial/WP46.yaml  
  /WP48:  
    $ref: paths/activitycategoryspecial/WP48.yaml  
  /B402:  
    $ref: paths/querymovements/B402.yaml  
  /B401:  
    $ref: paths/querymovements/B401.yaml  
  /BG61 DEPOSITO EFECTIVO CTE - AHORRO:  
    $ref: paths/passivetermfinan/BG61 DEPOSITO EFECTIVO CTE - AHORRO.yaml  
  /BQ10:  
    $ref: paths/passivetermfinan/BQ10.yaml  
  /B533:  
    $ref: paths/passivetermfinan/B533.yaml  
  /BGV3:  
    $ref: paths/passivetermfinan/BGV3.yaml  
  /B581:  
    $ref: paths/passivetermfinan/B581.yaml  
  /BKV4:  
    $ref: paths/checkinquiry/BKV4.yaml  
  /BQ05:  
    $ref: paths/checkinquiry/BQ05.yaml  
  /BKV1:  
    $ref: paths/checkinquiry/BKV1.yaml  
  /BKXA:  
    $ref: paths/checkinquiry/BKXA.yaml  
  /EXRG:  
    $ref: paths/exchangeinter/EXRG.yaml  
  /EXIC - menudeo:  
    $ref: paths/exchangeinter/EXIC - menudeo.yaml  
  /EXRI:  
    $ref: paths/exchangeinter/EXRI.yaml  
  /EXCV:  
    $ref: paths/exchangeinter/EXCV.yaml  
  /EXID:  
    $ref: paths/exchangeinter/EXID.yaml  
  /B030:  
    $ref: paths/digitalaccountopening/B030.yaml  
  /B032:  
    $ref: paths/digitalaccountopening/B032.yaml  
  /WP62:  
    $ref: paths/maintenancerelatedcom/WP62.yaml  
  /PE98:  
    $ref: paths/maintenancerelatedcom/PE98.yaml  
  /PE81:  
    $ref: paths/maintenancerelatedcom/PE81.yaml  
  /PE94:  
    $ref: paths/maintenancerelatedcom/PE94.yaml  
  /PEA1:  
    $ref: paths/maintenancerelatedcom/PEA1.yaml  
  /PEA7:  
    $ref: paths/maintenancerelatedcom/PEA7.yaml  
  /PEA8:  
    $ref: paths/maintenancerelatedcom/PEA8.yaml  
  /PE53:  
    $ref: paths/mtdatcomplmleglpers/PE53.yaml  
  /PE54:  
    $ref: paths/mtdatcomplmleglpers/PE54.yaml  
  /PE55:  
    $ref: paths/mtdatcomplmleglpers/PE55.yaml  
  /PE58:  
    $ref: paths/mtdatcomplmleglpers/PE58.yaml  
  /PE61:  
    $ref: paths/mtdatcomplmleglpers/PE61.yaml  
  /PE67:  
    $ref: paths/mtdatcomplmleglpers/PE67.yaml  
  /PE60:  
    $ref: paths/legalclientdomicile/PE60.yaml  
  /PE62:  
    $ref: paths/legalclientdomicile/PE62.yaml  
  /PE63 NATURAL:  
    $ref: paths/basiccustomerdata/PE63 NATURAL.yaml  
  /PE68:  
    $ref: paths/basiccustomerdata/PE68.yaml  
  /PE72 NATURAL:  
    $ref: paths/basiccustomerdata/PE72 NATURAL.yaml  
  /MP4Z:  
    $ref: paths/cardcontractcurrency/MP4Z.yaml  
  /MPK3:  
    $ref: paths/cardcontractcurrency/MPK3.yaml  
  /MP8X:  
    $ref: paths/checkcarddetails/MP8X.yaml  
  /MPCD:  
    $ref: paths/checkcarddetails/MPCD.yaml  
  /MP5C:  
    $ref: paths/checkcarddetails/MP5C.yaml  
  /MPK2:  
    $ref: paths/checkcarddetails/MPK2.yaml  
  /MPV0:  
    $ref: paths/checkcarddetails/MPV0.yaml  
  /VXP2 CONSULTA:  
    $ref: paths/interbankp2p/VXP2 CONSULTA.yaml  
  /VXAF CONSULTA:  
    $ref: paths/customerkeyphone/VXAF CONSULTA.yaml  
  /PE52:  
    $ref: paths/settlementsmaintenance/PE52.yaml  
  /PE80:  
    $ref: paths/settlementsmaintenance/PE80.yaml  
  /PE88:  
    $ref: paths/settlementsmaintenance/PE88.yaml  
  /PE97:  
    $ref: paths/settlementsmaintenance/PE97.yaml  
  /PE90:  
    $ref: paths/settlementsmaintenance/PE90.yaml  
  /PEV3:  
    $ref: paths/settlementsmaintenance/PEV3.yaml  
  /B036:  
    $ref: paths/normativecompaccounts/B036.yaml  
  /PE84:  
    $ref: paths/customerrelationship/PE84.yaml  
  /VPTF:  
    $ref: paths/preassignedcard/VPTF.yaml  
  /SRPI:  
    $ref: paths/collectiontermfinan/SRPI.yaml  
  /B731:  
    $ref: paths/checkdataaccount/B731.yaml  
  /B532:  
    $ref: paths/checkdataaccount/B532.yaml  
  /B793:  
    $ref: paths/checkdataaccount/B793.yaml  
  /QGBF:  
    $ref: paths/architecturetermfinan/QGBF.yaml  
  /QG81:  
    $ref: paths/architecturetermfinan/QG81.yaml  
  /QG83:  
    $ref: paths/architecturetermfinan/QG83.yaml  
  /QG00:  
    $ref: paths/architecturetermfinan/QG00.yaml  
  /QG01:  
    $ref: paths/architecturetermfinan/QG01.yaml  
  /MPK7:  
    $ref: paths/checkcardbalance/MPK7.yaml  
  /MP5D:  
    $ref: paths/checkcardbalance/MP5D.yaml  
  /MPL1:  
    $ref: paths/checkcardbalance/MPL1.yaml  
  /MP9Z:  
    $ref: paths/checkcardbalance/MP9Z.yaml 
  /MP5A:  
    $ref: paths/cardmanagment/MP5A.yaml  
  /MPB8:  
    $ref: paths/cardmanagment/MPB8.yaml  
  /MPAN:  
    $ref: paths/cardmanagment/MPAN.yaml  
  /MPAL:  
    $ref: paths/cardmanagment/MPAL.yaml  
  /MPV8:  
    $ref: paths/cardmanagment/MPV8.yaml  
  /B421:  
    $ref: paths/consuserviaccou/B421.yaml  
  /PF58:  
    $ref: paths/userconsult/PF58.yaml  
  /PEF2:  
    $ref: paths/userconsult/PEF2.yaml  
  /PE65:  
    $ref: paths/complementdataconsult/PE65.yaml  
  /PE48:  
    $ref: paths/complementdataconsult/PE48.yaml  
  /PE59:  
    $ref: paths/complementdataconsult/PE59.yaml  
  /PE50:  
    $ref: paths/complementdataconsult/PE50.yaml  
  /PE51:  
    $ref: paths/complementdataconsult/PE51.yaml  
  /PE85:  
    $ref: paths/complementdataconsult/PE85.yaml  
  /PEM2:  
    $ref: paths/maintenancebankrefer/PEM2.yaml  
  /PEM1:  
    $ref: paths/maintenancebankrefer/PEM1.yaml  
  /PF57:  
    $ref: paths/userconsult/PF57.yaml  
  /PE75:  
    $ref: paths/maintenancebankrefer/PE75.yaml  
  /PE83:  
    $ref: paths/maintenancebankrefer/PE83.yaml  
  /PE74:  
    $ref: paths/customerphone/PE74.yaml  
  /PE46:  
    $ref: paths/customerphone/PE46.yaml  
  /WP65:  
    $ref: paths/peprelationship/WP65.yaml  
  /WP43:  
    $ref: paths/peprelationship/WP43.yaml  
  /WP50:  
    $ref: paths/peprelationship/WP50.yaml  
  /WP64:  
    $ref: paths/peprelationship/WP64.yaml  
  /WP42:  
    $ref: paths/peprelationship/WP42.yaml  
  /WP49:  
    $ref: paths/peprelationship/WP49.yaml  
  /WP52:  
    $ref: paths/peprelationship/WP52.yaml  
  /VXPC CONSULTA:  
    $ref: paths/registrationp2c/VXPC CONSULTA.yaml  
  /WP51:  
    $ref: paths/suppliercustomermant/WP51.yaml  
  /WF71:  
    $ref: paths/incomemaintenancelegal/WF71.yaml  
  /PE64:  
    $ref: paths/incomemaintenancelegal/PE64.yaml  
  /PEAC:  
    $ref: paths/incomemaintenancelegal/PEAC.yaml  
  /PEAM:  
    $ref: paths/incomemaintenancelegal/PEAM.yaml  
  /PE56:  
    $ref: paths/incomemaintenancelegal/PE56.yaml  
  /PEV2:  
    $ref: paths/incomemaintenancelegal/PEV2.yaml  
  /WP55:  
    $ref: paths/legalclientmanagement/WP55.yaml  
  /WP56:  
    $ref: paths/legalclientmanagement/WP56.yaml  
  /WP59:  
    $ref: paths/legalclientmanagement/WP59.yaml  
  /WP60:  
    $ref: paths/legalclientmanagement/WP60.yaml  
  /WP61:  
    $ref: paths/legalclientmanagement/WP61.yaml  
  /WP53:  
    $ref: paths/subsidiaryoffices/WP53.yaml  
  /WP54:  
    $ref: paths/subsidiaryoffices/WP54.yaml  
  /B521:  
    $ref: paths/accountcloser/B521.yaml  
  /EX11:  
    $ref: paths/registerconsignment/EX11.yaml  
  /EX12:  
    $ref: paths/reverseconsignment/EX12.yaml  
  /Crear usuario master:  
    $ref: paths/Usuario Master/Crear usuario master.yaml  
  /Autorizar usuario master:  
    $ref: paths/Usuario Master/Autorizar usuario master.yaml  
  /Eliminar usuario master:  
    $ref: paths/Usuario Master/Eliminar usuario master.yaml  
  /Activar usuario master:  
    $ref: paths/Usuario Master/Activar usuario master.yaml  
  /Consulta usuario master:  
    $ref: paths/Usuario Master/Consulta usuario master.yaml  
  /Crear empresas:  
    $ref: paths/Usuario Master/Crear empresas.yaml  
  /Modificar empresas:  
    $ref: paths/Usuario Master/Modificar empresas.yaml  
  /Consulta empresas:  
    $ref: paths/Usuario Master/Consulta empresas.yaml  
components:
  securitySchemes:
    main_auth:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: 'http://example.com/api/oauth/dialog'
          scopes:
            'read:users': read users info
            'write:users': modify or remove users
    api_key:
      type: apiKey
      in: header
      name: api_key
    basic_auth:
      type: http
      scheme: basic
